sudo: required

language: php
php: 7.2

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/../easyengine/vendor/bin:$PATH"
    - TEST_COMMAND="site-command"

before_script:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - ./ci/prepare.sh

script:
  - cd "$TRAVIS_BUILD_DIR/../easyengine"
  - ./vendor/bin/behat

notifications:
  email:
    on_success: never
    on_failure: change